<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Gestion de la langue FR / EN pour SMTP DKIM.
 * La preference est sauvegardee par utilisateur (user_meta).
 * Acces : add_query_arg('smtpdkimc_lang','fr') ou add_query_arg('smtpdkimc_lang','en')
 */
class smtpdkimc_Lang {

    /** @var string 'fr' ou 'en' */
    private string $lang;

       public function __construct() {
        $uid = get_current_user_id();

        // ✅ Correction : Ajout nonce + wp_unslash()
        if ( isset( $_GET['smtpdkimc_lang'] ) && isset( $_GET['_wpnonce'] ) && in_array( $_GET['smtpdkimc_lang'], ['fr','en'], true ) ) {
            if ( wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ) ), 'smtpdkimc_lang_switch' ) ) {
                update_user_meta( $uid, 'smtpdkimc_lang', sanitize_text_field( wp_unslash( $_GET['smtpdkimc_lang'] ) ) );
                wp_safe_redirect( remove_query_arg( array( 'smtpdkimc_lang', '_wpnonce' ) ) );
                exit;
            }
        }

        $saved = get_user_meta( $uid, 'smtpdkimc_lang', true );
        $this->lang = in_array( $saved, ['fr','en'], true ) ? $saved : 'fr';
    }

    /** Retourne 'fr' ou 'en' */
    public function get(): string { return $this->lang; }

        /** Affiche la barre de sélection FR / EN */
    public function render_switcher(): void {
        $page_url = admin_url( 'admin.php?page=smtp-dkim' );
        // ✅ Correction : Ajouter le nonce dans l'URL
        $nonce    = wp_create_nonce( 'smtpdkimc_lang_switch' );
        $url_fr   = esc_url( add_query_arg( array( 'smtpdkimc_lang' => 'fr', '_wpnonce' => $nonce ), $page_url ) );
        $url_en   = esc_url( add_query_arg( array( 'smtpdkimc_lang' => 'en', '_wpnonce' => $nonce ), $page_url ) );
        $active   = 'display:inline-flex;align-items:center;gap:5px;background:#0073aa;color:#fff;padding:5px 14px;border-radius:20px;font-size:12px;font-weight:700;cursor:default';
        $inactive = 'display:inline-flex;align-items:center;gap:5px;background:#f0f0f1;color:#555;padding:5px 14px;border-radius:20px;font-size:12px;font-weight:600;text-decoration:none;border:1px solid #ddd;transition:background .15s';
        ?>
<div style="display:flex;align-items:center;gap:8px;margin:0 0 18px;padding:10px 16px;background:#fff;border:1px solid #e0e0e0;border-radius:6px;width:fit-content">
    <span style="font-size:12px;color:#888;margin-right:4px">🌐 <?php echo $this->lang === 'fr' ? 'Langue' : 'Language'; ?> :</span>
    <?php if ( $this->lang === 'fr' ): ?>
        <span style="<?php echo esc_attr( $active ); ?>">🇫🇷 Français</span>
        <a href="<?php echo esc_url( $url_en ); ?>" style="<?php echo esc_attr( $inactive ); ?>">🇬🇧 English</a>
    <?php else: ?>
        <a href="<?php echo esc_url( $url_fr ); ?>" style="<?php echo esc_attr( $inactive ); ?>">🇫🇷 Français</a>
        <span style="<?php echo esc_attr( $active ); ?>">🇬🇧 English</span>
    <?php endif; ?>
</div>
<?php
    }

    /**
     * Traduit une chaîne. Utilisation : $lang->t('save_config')
     * Retourne la chaîne FR si lang=fr, EN si lang=en.
     */
    public function t( string $key ): string {
        static $strings = null;
        if ( $strings === null ) { $strings = $this->load_strings(); }
        $s = $strings[ $this->lang ] ?? $strings['fr'];
        return $s[ $key ] ?? $key;
    }

    private function load_strings(): array {
        return [
            'fr' => [
                // Activation
                'activate_card_title'  => '🔌 Activation SMTP',
                'activate_checkbox'    => 'Activer SMTP DKIM',
                'activate_desc'        => 'Utiliser cette configuration pour <strong>tous les emails WordPress</strong>',
                'status_on'            => '✓ ACTIF — SMTP DKIM gère l\'envoi de tous vos emails WordPress.',
                'status_off_badge'     => 'ℹ️ Configuration WordPress par défaut active',
                'status_off_desc'      => 'En cochant cette option, <strong>SMTP DKIM</strong> remplacera la configuration email de WordPress par vos paramètres SMTP et votre signature DKIM. Tant que cette case n\'est pas cochée, WordPress continue d\'envoyer les emails avec sa méthode par défaut (PHP mail) <strong>mais sans vérification DKIM — vos emails risquent d\'atterrir dans les spams de vos clients.</strong>',
                'conflict_warn'        => '⚠️ <strong>WP Mail SMTP détecté.</strong> Désactivez-le pour éviter les conflits.',
                // Sender
                'sender_card_title'    => '✉️ Expéditeur',
                'email_from_label'     => 'Email From',
                'email_from_desc'      => 'Adresse email visible par les destinataires.',
                'from_name_label'      => 'Nom d\'expéditeur',
                'force_from_label'     => 'Forcer l\'expéditeur',
                'force_from_desc'      => 'Forcer l\'adresse From sur tous les emails sortants',
                // SMTP Server
                'smtp_card_title'      => '🖥️ Serveur SMTP',
                'smtp_privacy'         => '🔒 <strong>Vos informations sont stockées uniquement dans votre base de données WordPress.</strong> Le mot de passe est chiffré AES-256-CBC avant stockage. <strong>Aucune configuration, aucun mot de passe et aucune donnée personnelle ne sont envoyés ou enregistrés sur les serveurs de smtp-dkim.com.</strong>',
                'smtp_host_label'      => 'SMTP Host',
                'smtp_host_desc'       => 'Nom du serveur fourni par votre hébergeur.',
                'enc_label'            => 'Chiffrement',
                'port_label'           => 'Port SMTP',
                'auto_tls_label'       => 'Auto TLS',
                'auto_tls_desc'        => 'Activer l\'upgrade automatique vers TLS',
                'auth_label'           => 'SMTP Auth',
                'auth_desc'            => 'Authentification SMTP (recommandé)',
                'user_label'           => 'Nom d\'utilisateur',
                'pwd_label'            => 'Mot de passe',
                'pwd_placeholder_keep' => '(laisser vide pour conserver)',
                'pwd_placeholder_new'  => 'Entrez le mot de passe SMTP',
                'pwd_ok'               => '🔒 Mot de passe chiffré en DB (AES-256-CBC). Laissez vide pour conserver.',
                'pwd_warn'             => '⚠️ Non chiffré — re-sauvegardez pour chiffrer.',
                'pwd_missing'          => '⚠ Aucun mot de passe enregistré.',
                'pwd_note'             => 'Chiffré avec <strong>AES-256-CBC</strong> (clé : <code>SECURE_AUTH_KEY</code>).',
                'debug_label'          => 'Niveau de debug',
                'debug_0' => '0 — Désactivé (production)\', \'debug_1\' => \'1 — Erreurs seulement',
                'debug_2' => '2 — Messages serveur\',       \'debug_3\' => \'3 — Serveur + client',
                'debug_4' => '4 — Verbose complet',
                // DKIM
                'dkim_card_title'      => '🔐 Signature DKIM',
                'lic_active_badge'     => '✓ Licence active',
                'lic_required_badge'   => '🔒 Licence smtp-dkim requise',
                'dkim_locked_info'     => '🔒 Les champs DKIM sont verrouillés. Achetez et activez une licence pour les débloquer — <a href="https://smtp-dkim.com" target="_blank"><strong>smtp-dkim.com</strong></a>. Une fois la licence activée, le domaine et le sélecteur seront remplis automatiquement.',
                'dkim_active_info'     => 'La signature DKIM signe cryptographiquement chaque email sortant. Gmail, Outlook et Yahoo vérifient cette signature pour confirmer que l\'email provient bien de votre domaine.',
                'dkim_domain_label'    => 'Domaine DKIM',
                'dkim_domain_auto'     => '✓ Rempli automatiquement à partir de votre domaine WordPress',
                'dkim_domain_desc'     => 'Laissez vide pour utiliser automatiquement le domaine du site.',
                'dkim_sel_label'       => 'Sélecteur DKIM',
                'dkim_sel_auto'        => '✓ Détecté automatiquement dans votre DNS — enregistrement',
                'dkim_sel_desc'        => 'Détecté automatiquement dans le DNS lors de l\'activation de la licence.',
                'dkim_key_label'       => 'Clé privée DKIM',
                'dkim_key_needed'      => '⭐ À coller depuis cPanel',
                'dkim_key_ok'          => '✓ Clé privée enregistrée',
                'dkim_key_ok2'         => 'caractères. DKIM actif.',
                'dkim_key_missing'     => '✗ Clé privée manquante — DKIM inactif tant que ce champ n\'est pas rempli.',
                'dkim_key_locked'      => 'Ce champ sera accessible après activation de votre licence.',
                'dkim_where_key'       => '📍 Où trouver la clé privée : cPanel → <strong>Email Deliverability</strong> → votre domaine → <strong>DKIM</strong> → <strong>View / Afficher</strong> → copiez le bloc <strong>Private Key</strong> (de <code>-----BEGIN RSA PRIVATE KEY-----</code> à <code>-----END RSA PRIVATE KEY-----</code>).',
                'dkim_why'             => 'ℹ️ <strong>Pourquoi cette clé ne peut pas être détectée automatiquement ?</strong> DKIM utilise deux clés : la <strong>clé publique</strong> (dans votre DNS, détectée automatiquement) sert à vérifier la signature, et la <strong>clé privée</strong> sert à signer chaque email. La clé privée n\'est <strong>jamais publiée dans le DNS</strong>. Elle est stockée uniquement dans votre base de données WordPress. <strong>Aucune donnée n\'est envoyée sur les serveurs de smtp-dkim.com.</strong>',
                'dkim_buy_btn'         => '🛒 Acheter une licence sur smtp-dkim.com',
                // Save
                'save_btn'             => '💾 Enregistrer la configuration',
                'save_ok'              => '✓ Configuration enregistrée.',
                'save_err'             => '✗ Erreur lors de la sauvegarde.',
                // Licence
                'lic_card_title'       => '🔑 Licence SMTP-DKIM',
                'lic_active_label'     => '✓ Licence active',
                'lic_key_row'          => 'Clé :',
                'lic_domain_row'       => 'Domaine :',
                'lic_exp_row'          => 'Expiration :',
                'lic_check_row'        => 'Dernière vérification :',
                'lic_deactivate'       => 'Inactiver la licence',
                'lic_deactivate_cfm'   => 'Inactiver la licence sur ce site ? Vous pourrez la réactiver sur n\'importe quel domaine.',
                'lic_deactivate_explain' => 'En inactivant la licence, la signature DKIM sera désactivée sur ce site. Vous pourrez réactiver cette même licence sur ce site ou sur un autre domaine à tout moment. La date d\'expiration de votre licence reste inchangée.',
                'test_holder_explain'  => '📧 Cet email est envoyé au détenteur de la licence — l\'adresse enregistrée lors de l\'achat. Il contient le rapport complet de configuration (SMTP, DKIM, DNS, statut de licence).',
                'test_external_title'  => '🔍 Test d\'envoi vers une adresse externe',
                'test_external_explain'=> 'Envoyez un email de test vers n\'importe quelle adresse pour vérifier si vos emails arrivent en boîte de réception ou dans les spams. Cet email ne contient pas les détails de votre licence — il s\'agit d\'un simple message de test pour des raisons de sécurité.',
                'test_external_label'  => 'Adresse email destinataire',
                'test_external_btn'    => '📤 Envoyer le test externe',
                'test_external_security' => '🔒 Pour des raisons de sécurité, les détails de votre licence ne sont jamais inclus dans les emails de test envoyés vers des adresses externes.',
                'lic_none'             => '✗ Aucune licence enregistrée sur ce site.',
                'lic_invalid'          => '✗ Licence invalide ou refusée par smtp-dkim.com.',
                'lic_deactivated'      => '✗ Licence inactive — vous pouvez la réactiver sur ce site ou un autre.',
                'lic_expired_badge'    => '⚠️ Licence expirée.',
                'lic_expired_note'     => 'Votre clé privée DKIM reste enregistrée dans la base de données — elle n\'est pas supprimée. La signature DKIM est désactivée tant que la licence n\'est pas renouvelée. Vos emails continuent d\'être envoyés via SMTP, sans signature DKIM. <strong>Pour réactiver :</strong> entrez une nouvelle clé de licence ci-dessous.',
                'lic_buy_at'           => 'Achetez ou renouvelez sur',
                'lic_buy_then'         => 'puis entrez votre clé :',
                'lic_activate_btn'     => '✔ Activer',
                'lic_activate_desc'    => 'La clé sera validée en temps réel. Le domaine et le sélecteur DKIM seront détectés automatiquement.',
                // Post-activation missing key banner
                'lic_missing_title'    => '⚠️ Dernière étape manquante : la clé privée DKIM',
                'lic_missing_body'     => 'Votre licence est active et le sélecteur a été détecté automatiquement. La signature DKIM est encore <strong>inactive</strong> car le plugin a besoin de votre <strong>clé privée</strong> — elle se trouve uniquement dans <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong>.',
                'lic_missing_priv'     => '🔒 <strong>Confidentialité :</strong> Votre clé privée est enregistrée uniquement dans votre base de données WordPress. <strong>Aucune donnée n\'est envoyée sur les serveurs de smtp-dkim.com.</strong>',
                'need_key_remind'      => '⚠️ Clé privée DKIM manquante. Collez votre clé depuis <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong> puis enregistrez.',
                // Test email
                'test_card_title'      => '📋 Envoyer le rapport de licence',
                'test_send_to'         => 'Envoi vers',
                'test_btn'             => '📨 Envoyer le rapport de licence',
                // Summary
                'sum_card_title'       => '📋 Configuration SMTP-DKIM',
                'sum_smtp'             => 'SMTP',
                'sum_from'             => 'Email From',
                'sum_host'             => 'SMTP Host',
                'sum_enc'              => 'Chiffrement',
                'sum_user'             => 'Utilisateur',
                'sum_pwd'              => 'Mot de passe',
                'sum_lic'              => 'Licence SMTP-DKIM',
                'sum_dkim'             => 'SMTP-DKIM (plugin)',
                'sum_spf'              => 'SPF (DNS)',
                'sum_dkim_dns'         => 'Clé Publique DKIM (DNS)',
                'sum_dmarc'            => 'DMARC (DNS)',
                'sum_debug'            => 'Debug SMTP',
                'sum_not_cfg'          => 'Non configuré',
                'sum_pwd_enc'          => '🔒 Chiffré (AES-256-CBC)',
                'sum_pwd_plain'        => '⚠️ Non chiffré — re-sauvegardez',
                'sum_lic_active'       => '✓ Active',
                'sum_lic_expired'      => '⚠️ Expirée — Renouveler',
                'sum_lic_invalid'      => '✗ Invalide — Vérifier',
                'sum_lic_none'         => '✗ Aucune — Acheter',
                'sum_dkim_active_pfx'  => '✓ Actif —',
                'sum_dkim_no_lic'      => '🔒 Licence requise',
                'sum_dkim_no_key'      => '✗ Clé privée manquante',
                'sum_level'            => 'Niveau',
                'sum_dns_note'         => 'DNS vérifié il y a moins d\'1 heure via Cloudflare DoH.',
                'sum_dns_scan'         => 'Relancer le scan ↓',
                'sum_fix_link'         => 'Voir le diagnostic ↓',
                // DNS Diagnostic
                'dns_card_title'       => '🔍 Diagnostic DNS — SPF · Clé Publique DKIM · DMARC',
                'dns_desc'             => 'Vérifiez que vos enregistrements DNS sont correctement configurés. Scan via DNS-over-HTTPS Cloudflare (port 443 — universel).',
                'dns_domain_lbl'       => 'Domaine',
                'dns_sel_lbl'          => 'Sélecteur DKIM',
                'dns_scan_btn'         => '🔍 Lancer le scan DNS',
                'dns_manual_lbl'       => 'Vérification manuelle via MXToolbox :',
                'dns_to_fix'           => 'À corriger',
                'dns_missing'          => 'Absent / Erreur',
                'lic_renew'            => 'Renouveler',
                'dns_all_ok'           => 'Parfait ! SPF, DKIM et DMARC sont correctement configurés. Vos emails ne tomberont plus dans les spams.',
                // Nouveaux strings complets v11
                'test_card_title'         => '📋 Envoyer le rapport de licence',
                'test_btn'                => '📨 Envoyer le rapport de licence',
                'test_send_to_lbl'        => 'Envoi vers',
                'test_success_msg'        => 'Email envoyé à',
                'test_fail_msg'           => 'Échec :',
                'sender_card_title_lbl'   => '✉️ Expéditeur',
                'pwd_encrypted_note'      => '🔒 Mot de passe chiffré en DB (AES-256-CBC). Laissez vide pour conserver.',
                'pwd_aes_note'            => 'Chiffré avec <strong>AES-256-CBC</strong> (clé : <code>SECURE_AUTH_KEY</code>).',
                'dkim_key_encrypted_note' => '🔒 Clé privée DKIM chiffrée en DB (AES-256-CBC).',
                'dns_manual_lbl'          => 'Vérification manuelle via MXToolbox :',
                'spf_softfail_lbl'        => 'Politique : ~all (SoftFail)',
                'spf_strict_lbl'          => 'Politique : -all (Strict ✓)',
                'spf_neutral_lbl'         => 'Politique : ?all (Neutre)',
                'dkim_pub_key_lbl'        => 'Clé Privée DKIM',
                'dkim_scroll_note'        => 'Faites défiler pour voir la clé complète.',
                'dkim_key_size_lbl'       => 'Taille de la clé :',
                'dkim_optimal_lbl'        => '✓ (sécurité optimale)',
                'dkim_min_bits_lbl'       => '— minimum recommandé : 2048 bits',
                'dmarc_policy_lbl'        => 'Politique :',
                'dmarc_no_rua_warn'       => '⚠ Pas de rua=',
                'dmarc_optional_note'     => 'Optionnel',
                'dmarc_rua_info'          => '💬 Pas de rua= - vous ne recevrez pas les rapports DMARC (optionnel mais recommandé).',
                'dmarc_rua_fix'           => '💬 (Optionnel) Ajoutez rua= pour recevoir les rapports DMARC. Non requis pour la délivrabilité.',
                'overlay_title'           => 'Activation en cours…',
                'overlay_step1'           => 'Étape 1/3 — Validation de la clé',
                'overlay_step2'           => 'Étape 2/3 — Analyse DNS',
                'overlay_step3'           => 'Étape 3/3 — Remplissage des champs DKIM',
                'overlay_msg1'            => 'Validation de la licence auprès de smtp-dkim.com…',
                'overlay_msg2'            => 'Détection du sélecteur DKIM dans votre DNS…',
                'overlay_msg4'            => 'Activation en cours…',
                'overlay_sel_found'       => 'Sélecteur DKIM détecté automatiquement !',
                'overlay_sel_manual'      => 'Domaine configuré. Entrez votre clé privée DKIM manuellement.',
                'overlay_alert_empty'     => 'Veuillez entrer une clé de licence.',
                'cpanel_steps_title'      => '📍 Comment obtenir votre clé privée DKIM dans cPanel :',
                'why_not_auto_title'      => 'ℹ️ Pourquoi cette clé ne peut pas être détectée automatiquement ?',
                'why_not_auto_text'       => 'Le scan DNS affiche votre <strong>clé publique</strong> DKIM — celle visible par tout le monde et qui sert à vérifier la signature. La <strong>clé privée</strong> est différente : elle reste secrète sur votre serveur et sert à signer chaque email. C\'est le principe de la cryptographie asymétrique RSA — il est mathématiquement impossible de déduire la clé privée à partir de la clé publique, ce qui garantit la sécurité de vos emails.',
                'lic_max_activations'     => 'Nombre maximum d\'activations atteint. Contactez smtp-dkim.com.',
                'lic_expire_explain_full' => 'ℹ️ <strong>Ce qui se passe à l\'expiration de la licence :</strong> Votre clé privée DKIM reste enregistrée dans votre base de données — elle n\'est pas supprimée. La signature DKIM est désactivée sur tous les emails sortants jusqu\'au renouvellement. Vos emails continuent d\'être envoyés normalement via SMTP, sans signature DKIM. <strong>Pour réactiver :</strong> renouvelez votre licence sur smtp-dkim.com et entrez la nouvelle clé ci-dessous.',
                'sum_card_title'          => '📋 Configuration SMTP-DKIM',
                'lic_notice_found'        => 'Sélecteur DKIM détecté automatiquement :',
                'lic_notice_default'      => 'Sélecteur DKIM par défaut : default (vérifiez dans cPanel si nécessaire)',
                'lic_activation_success'  => 'Licence activée avec succès. La fonctionnalité DKIM est maintenant disponible.',

                'sum_level'            => 'Niveau',
                // Explanations — all long texts
                'email_from_placeholder'  => 'noreply@your-domain.com',
                'smtp_host_placeholder'   => 'mail.your-domain.com',
                'smtp_host_desc'          => 'Nom du serveur SMTP fourni par votre hébergeur.',
                'enc_ssl'                 => 'SSL (port 465)',
                'enc_tls'                 => 'TLS / STARTTLS (port 587)',
                'enc_none'                => 'Aucun (port 25)',
                'auto_tls_desc_full'      => 'Activer l\'upgrade automatique vers TLS',
                'auth_desc_full'          => 'Authentification SMTP (recommandé)',
                'force_from_desc_full'    => 'Forcer l\'adresse From sur tous les emails sortants',
                'pwd_placeholder_keep'    => '(laisser vide pour conserver)',
                'pwd_placeholder_new'     => 'Entrez le mot de passe SMTP',
                'dkim_domain_auto_desc'   => '✓ Rempli automatiquement à partir de votre domaine WordPress',
                'dkim_domain_manual_desc' => 'Laissez vide pour utiliser automatiquement le domaine du site.',
                'dkim_sel_auto_desc'      => '✓ Détecté automatiquement dans votre DNS — enregistrement',
                'dkim_sel_manual_desc'    => 'Détecté automatiquement dans le DNS lors de l\'activation de la licence.',
                'dkim_key_needed_star'    => '⭐ À coller depuis cPanel',
                'dkim_key_placeholder'    => "(Copiez ici TOUTE la clé privée depuis cPanel
→ Email Deliverability → DKIM → View → Private Key)",
                'dkim_key_ok_msg'         => '✓ Clé privée enregistrée — ',
                'dkim_key_ok_sfx'         => ' caractères. DKIM actif.',
                'dkim_key_missing_msg'    => '✗ Clé privée manquante — DKIM inactif tant que ce champ n\'est pas rempli.',
                'dkim_key_locked_msg'     => 'Ce champ sera accessible après activation de votre licence.',
                'dkim_cpanel_steps_title' => '📍 Comment obtenir votre clé privée DKIM dans cPanel :',
                'dkim_cpanel_step1'       => 'Connectez-vous à votre <strong>cPanel</strong> (votre hébergeur)',
                'dkim_cpanel_step2'       => 'Section <strong>Email</strong> → cliquez <strong>Email Deliverability</strong>',
                'dkim_cpanel_step3_pfx'   => 'Repérez le domaine',
                'dkim_cpanel_step3_sfx'   => 'dans la liste',
                'dkim_cpanel_step4'       => 'Cliquez <strong>Manage / Gérer</strong> à droite de ce domaine',
                'dkim_cpanel_step5'       => 'Cherchez la section <strong>DKIM</strong> et cliquez <strong>View / Afficher</strong>',
                'dkim_cpanel_step6'       => 'Copiez <strong>TOUT le bloc "Private Key"</strong> (clé privée), de la première ligne',
                'dkim_cpanel_step7'       => 'jusqu\'à la dernière ligne',
                'dkim_cpanel_step8'       => 'Collez la clé dans le champ de texte ci-dessus',
                'dkim_cpanel_step9'       => 'Cliquez <strong>Enregistrer la configuration</strong>',
                'dkim_why_title'          => 'ℹ️ Pourquoi cette clé ne peut pas être détectée automatiquement ?',
                'dkim_why_text'           => 'DKIM utilise deux clés : la <strong>clé publique</strong> (dans votre DNS, détectée automatiquement) sert à vérifier la signature. La <strong>clé privée</strong> sert à signer chaque email et n\'est <strong>jamais publiée dans le DNS</strong> — elle reste secrète sur votre serveur, ce qui garantit que personne d\'autre ne peut signer en votre nom. Elle est stockée uniquement dans votre base de données WordPress. <strong>Aucune donnée n\'est envoyée sur les serveurs de smtp-dkim.com.</strong>',
                'dkim_where_key_short'    => '📍 Où trouver votre clé : cPanel → <strong>Email Deliverability</strong> → votre domaine → <strong>DKIM</strong> → <strong>View</strong> → copiez <strong>Private Key</strong>',
                'dkim_locked_info_full'   => '🔒 Les champs DKIM sont verrouillés. Achetez et activez une licence pour les débloquer — <a href="https://smtp-dkim.com" target="_blank"><strong>smtp-dkim.com</strong></a>. Une fois la licence activée, le domaine et le sélecteur seront remplis automatiquement.',
                'dkim_active_info_full'   => 'La signature DKIM signe cryptographiquement chaque email sortant. Gmail, Outlook et Yahoo vérifient cette signature pour confirmer que l\'email provient bien de votre domaine et qu\'il n\'a pas été modifié en transit.',
                'missing_key_title'       => '⚠️ Dernière étape manquante : la clé privée DKIM',
                'missing_key_body'        => 'Votre licence est active et le sélecteur a été détecté automatiquement. La signature DKIM est encore <strong>inactive</strong> car le plugin a besoin de votre <strong>clé privée</strong> — elle se trouve uniquement dans <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong>.',
                'missing_key_privacy'     => '🔒 <strong>Confidentialité :</strong> Votre clé privée est enregistrée uniquement dans la base de données de votre WordPress. <strong>Aucune donnée n\'est envoyée sur les serveurs de smtp-dkim.com.</strong>',
                'need_key_remind_full'    => '⚠️ Clé privée DKIM manquante. La signature DKIM est inactive. Collez votre clé depuis <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong> puis enregistrez.',
                'lic_active_label_full'   => '✓ Licence active',
                'lic_key_lbl'             => 'Clé :',
                'lic_holder_lbl'          => 'Détenteur :',
                'lic_holder_name_lbl'     => 'Titulaire :',
                'lic_holder_email_lbl'    => 'Email titulaire :',
                'lic_plan_lbl'            => 'Plan :',
                'lic_domain_lbl'          => 'Domaine :',
                'lic_exp_lbl'             => 'Expiration :',
                'lic_check_lbl'           => 'Dernière vérification :',
                'lic_none_msg'            => '✗ Aucune licence enregistrée sur ce site.',
                'lic_invalid_msg'         => '✗ Licence invalide ou refusée par smtp-dkim.com.',
                'lic_deactivated_msg'     => '✗ Licence inactive — vous pouvez la réactiver sur ce site ou un autre.',
                'lic_expired_msg'         => '⚠️ <strong>Licence expirée.</strong>',
                'lic_expired_explain'     => 'Votre clé privée DKIM reste enregistrée dans la base de données — elle n\'est pas supprimée. La signature DKIM est désactivée sur tous les emails sortants tant que la licence n\'est pas renouvelée. Vos emails continuent d\'être envoyés normalement via SMTP, sans signature DKIM. <strong>Pour réactiver :</strong> entrez une nouvelle clé de licence valide ci-dessous.',
                'lic_buy_link_pfx'        => 'Achetez ou renouvelez sur',
                'lic_buy_link_sfx'        => 'puis entrez votre clé :',
                'lic_key_placeholder'     => 'SDKM-XXXXX-XXXXX-XXXXX-XXXXX',
                'lic_activate_note'       => 'La clé sera validée en temps réel. Le domaine et le sélecteur DKIM seront détectés automatiquement.',
                'lic_notice_found'        => 'Sélecteur DKIM détecté automatiquement :',
                'lic_notice_default'      => 'Sélecteur DKIM par défaut : default (vérifiez dans cPanel si nécessaire)',
                'sum_actif'               => 'ACTIF',
                'sum_inactif'             => 'INACTIF',
                'sum_buy_lnk'             => 'Acheter',
                'sum_check_lnk'           => 'Vérifier',
                'sum_renew_lnk'           => 'Renouveler',
                'sum_dkim_req'            => '🔒 Licence requise',
                'sum_dkim_nokey'          => '✗ Clé privée manquante',
                'sum_dns_scan_lnk'        => 'Relancer le scan ↓',
                'sum_fix_lnk'             => 'Voir le diagnostic ↓',
                'sum_dns_note_full'       => 'DNS vérifié via Cloudflare DoH.',
                'sum_unconfigured'        => 'Non configuré',
                'overlay_step1'           => 'Étape 1/3 — Validation de la clé',
                'overlay_step2'           => 'Étape 2/3 — Analyse DNS',
                'overlay_step3'           => 'Étape 3/3 — Remplissage des champs DKIM',
                'overlay_msg1'            => 'Validation de la licence auprès de smtp-dkim.com...',
                'overlay_msg2'            => 'Détection du sélecteur DKIM dans votre DNS...',
                'overlay_msg3'            => 'Configuration des champs DKIM...',
                'overlay_msg4'            => 'Activation en cours...',
                'overlay_sel_found'       => 'Sélecteur DKIM détecté automatiquement !',
                'overlay_sel_manual'      => 'Domaine configuré. Entrez votre clé privée DKIM manuellement.',
                'overlay_alert_empty'     => 'Veuillez entrer une clé de licence.',
                'dns_results_for'         => 'Résultats pour',
                'dns_pub_key_note'        => '🔒 <strong>Clé publique DKIM</strong> — visible dans le DNS, utilisée par Gmail/Outlook pour <em>vérifier</em> vos emails. Cette clé est <strong>différente</strong> de la clé privée à coller dans le plugin.',
                'dns_fix_optional'        => '💬 Information facultative',
                'dns_fix_how'             => '🔧 Comment corriger — cPanel → Zone Editor',
                'dns_fix_type'            => 'Type',
                'dns_fix_name'            => 'Nom',
                'dns_fix_value'           => 'Valeur',
                'dns_rsa_bits'            => 'bits',
                'dns_optimal'             => '✓ (sécurité optimale)',
                'dns_min_req'             => '— minimum recommandé : 2048 bits',
                'dns_alt_sel'             => 'fonctionne — mettez-le à jour dans le plugin.',
                'lic_card_title_full'     => '🔑 Licence SMTP-DKIM',
                'test_send_to_lbl'        => 'Envoi vers',
            ],
            'en' => [
                // Activation
                'activate_card_title'  => '🔌 SMTP Activation',
                'activate_checkbox'    => 'Enable SMTP DKIM',
                'activate_desc'        => 'Use this configuration for <strong>all WordPress emails</strong>',
                'status_on'            => '✓ ACTIVE — SMTP DKIM is handling all outgoing WordPress emails.',
                'status_off_badge'     => 'ℹ️ WordPress default email configuration active',
                'status_off_desc'      => 'By checking this option, <strong>SMTP DKIM</strong> will replace WordPress\'s default email system with your SMTP settings and DKIM signature. Until checked, WordPress sends emails via its default method (PHP mail) <strong>but without DKIM verification — your emails may land in your clients\' spam folders.</strong>',
                'conflict_warn'        => '⚠️ <strong>WP Mail SMTP detected.</strong> Disable it to avoid conflicts.',
                // Sender
                'sender_card_title'    => '✉️ Sender',
                'email_from_label'     => 'From Email',
                'email_from_desc'      => 'Email address visible to recipients.',
                'from_name_label'      => 'From Name',
                'force_from_label'     => 'Force From Email',
                'force_from_desc'      => 'Force the From address on all outgoing emails',
                // SMTP Server
                'smtp_card_title'      => '🖥️ SMTP Server',
                'smtp_privacy'         => '🔒 <strong>Your information is stored only in your WordPress database.</strong> The password is encrypted with AES-256-CBC before storage. <strong>No configuration data, passwords, or personal information are sent to or stored on smtp-dkim.com servers.</strong>',
                'smtp_host_label'      => 'SMTP Host',
                'smtp_host_desc'       => 'Server name provided by your hosting provider.',
                'enc_label'            => 'Encryption',
                'port_label'           => 'SMTP Port',
                'auto_tls_label'       => 'Auto TLS',
                'auto_tls_desc'        => 'Enable automatic upgrade to TLS if available',
                'auth_label'           => 'SMTP Auth',
                'auth_desc'            => 'SMTP Authentication (recommended)',
                'user_label'           => 'Username',
                'pwd_label'            => 'Password',
                'pwd_placeholder_keep' => '(leave blank to keep current)',
                'pwd_placeholder_new'  => 'Enter SMTP password',
                'pwd_ok'               => '🔒 Password encrypted in DB (AES-256-CBC). Leave blank to keep.',
                'pwd_warn'             => '⚠️ Not encrypted — re-save to encrypt.',
                'pwd_missing'          => '⚠ No password saved.',
                'pwd_note'             => 'Encrypted with <strong>AES-256-CBC</strong> (key: <code>SECURE_AUTH_KEY</code>).',
                'debug_label'          => 'Debug Level',
                'debug_0' => '0 — Disabled (production)\', \'debug_1\' => \'1 — Errors only',
                'debug_2' => '2 — Server messages\',       \'debug_3\' => \'3 — Server + client',
                'debug_4' => '4 — Full verbose',
                // DKIM
                'dkim_card_title'      => '🔐 DKIM Signature',
                'lic_active_badge'     => '✓ License active',
                'lic_required_badge'   => '🔒 smtp-dkim license required',
                'dkim_locked_info'     => '🔒 DKIM fields are locked. Purchase and activate a license to unlock — <a href="https://smtp-dkim.com" target="_blank"><strong>smtp-dkim.com</strong></a>. The domain and selector will be filled automatically after activation.',
                'dkim_active_info'     => 'DKIM signature cryptographically signs each outgoing email. Gmail, Outlook and Yahoo verify this signature to confirm the email genuinely comes from your domain.',
                'dkim_domain_label'    => 'DKIM Domain',
                'dkim_domain_auto'     => '✓ Auto-filled from your WordPress domain',
                'dkim_domain_desc'     => 'Leave blank to automatically use the site domain.',
                'dkim_sel_label'       => 'DKIM Selector',
                'dkim_sel_auto'        => '✓ Automatically detected in your DNS — record',
                'dkim_sel_desc'        => 'Automatically detected in DNS when the license is activated.',
                'dkim_key_label'       => 'DKIM Private Key',
                'dkim_key_needed'      => '⭐ Paste from cPanel',
                'dkim_key_ok'          => '✓ Private key saved',
                'dkim_key_ok2'         => 'characters. DKIM active.',
                'dkim_key_missing'     => '✗ Private key missing — DKIM inactive until this field is filled.',
                'dkim_key_locked'      => 'This field will be available after activating your license.',
                'dkim_where_key'       => '📍 Where to find the private key: cPanel → <strong>Email Deliverability</strong> → your domain → <strong>DKIM</strong> → <strong>View</strong> → copy the full <strong>Private Key</strong> block (from <code>-----BEGIN RSA PRIVATE KEY-----</code> to <code>-----END RSA PRIVATE KEY-----</code>).',
                'dkim_why'             => 'ℹ️ <strong>Why can\'t this key be detected automatically?</strong> DKIM uses two keys: the <strong>public key</strong> (in DNS, detected automatically) verifies the signature, and the <strong>private key</strong> signs each email. The private key is <strong>never published in DNS</strong>. It is stored only in your WordPress database. <strong>No data is sent to smtp-dkim.com servers.</strong>',
                'dkim_buy_btn'         => '🛒 Buy a license at smtp-dkim.com',
                // Save
                'save_btn'             => '💾 Save Configuration',
                'save_ok'              => '✓ Configuration saved.',
                'save_err'             => '✗ Error while saving.',
                // Licence
                'lic_card_title'       => '🔑 SMTP-DKIM License',
                'lic_active_label'     => '✓ License active',
                'lic_key_row'          => 'Key:',
                'lic_domain_row'       => 'Domain:',
                'lic_exp_row'          => 'Expires:',
                'lic_check_row'        => 'Last check:',
                'lic_deactivate'       => 'Set license inactive',
                'lic_deactivate_cfm'   => 'Set license inactive? You can reactivate it on any domain.',
                'lic_deactivate_explain' => 'By deactivating the license, DKIM signing will be disabled on this site. You can reactivate the same license on this site or any other domain at any time. Your license expiration date remains unchanged.',
                'test_holder_explain'  => '📧 This email is sent to the license holder — the address registered at purchase. It contains the full configuration report (SMTP, DKIM, DNS, license status).',
                'test_external_title'  => '🔍 Send a test to an external address',
                'test_external_explain'=> 'Send a test email to any address to check whether your emails arrive in the inbox or spam. This email does not contain your license details — it is a simple test message for security reasons.',
                'test_external_label'  => 'Recipient email address',
                'test_external_btn'    => '📤 Send external test',
                'test_external_security' => '🔒 For security reasons, your license details are never included in test emails sent to external addresses.',
                'lic_none'             => '✗ No license registered on this site.',
                'lic_invalid'          => '✗ License invalid or refused by smtp-dkim.com.',
                'lic_deactivated'      => '✗ License inactive — you can reactivate it on this or another site.',
                'lic_expired_badge'    => '⚠️ License expired.',
                'lic_expired_note'     => 'Your DKIM private key remains in the database — it is not deleted. DKIM signing is disabled until the license is renewed. Emails continue to be sent via SMTP, without DKIM signing. <strong>To reactivate:</strong> enter a new license key below.',
                'lic_buy_at'           => 'Buy or renew at',
                'lic_buy_then'         => 'then enter your key:',
                'lic_activate_btn'     => '✔ Activate',
                'lic_activate_desc'    => 'The key will be validated in real time. The DKIM domain and selector will be detected automatically.',
                // Post-activation missing key banner
                'lic_missing_title'    => '⚠️ Last step missing: the DKIM private key',
                'lic_missing_body'     => 'Your license is active and the selector was detected automatically. DKIM signing is still <strong>inactive</strong> because the plugin needs your <strong>private key</strong> — it\'s only in <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong>.',
                'lic_missing_priv'     => '🔒 <strong>Privacy:</strong> Your private key is stored only in your WordPress database. <strong>No data is sent to smtp-dkim.com servers.</strong>',
                'need_key_remind'      => '⚠️ DKIM private key missing. Paste your key from <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong> then save.',
                // Test email
                'test_card_title'      => '📋 Send License Report',
                'test_send_to'         => 'Sending to',
                'test_btn'             => '📨 Send license report',
                // Summary
                'sum_card_title'       => '📋 SMTP-DKIM Configuration',
                'sum_smtp'             => 'SMTP',
                'sum_from'             => 'From Email',
                'sum_host'             => 'SMTP Host',
                'sum_enc'              => 'Encryption',
                'sum_user'             => 'Username',
                'sum_pwd'              => 'Password',
                'sum_lic'              => 'SMTP-DKIM License',
                'sum_dkim'             => 'SMTP-DKIM (plugin)',
                'sum_spf'              => 'SPF (DNS)',
                'sum_dkim_dns'         => 'DKIM Public Key (DNS)',
                'sum_dmarc'            => 'DMARC (DNS)',
                'sum_debug'            => 'SMTP Debug',
                'sum_not_cfg'          => 'Not configured',
                'sum_pwd_enc'          => '🔒 Encrypted (AES-256-CBC)',
                'sum_pwd_plain'        => '⚠️ Not encrypted — re-save',
                'sum_lic_active'       => '✓ Active',
                'sum_lic_expired'      => '⚠️ Expired — Renew',
                'sum_lic_invalid'      => '✗ Invalid — Check',
                'sum_lic_none'         => '✗ None — Buy',
                'sum_dkim_active_pfx'  => '✓ Active —',
                'sum_dkim_no_lic'      => '🔒 License required',
                'sum_dkim_no_key'      => '✗ Private key missing',
                'sum_level'            => 'Level',
                'sum_dns_note'         => 'DNS verified less than 1 hour ago via Cloudflare DoH.',
                'sum_dns_scan'         => 'Re-run scan ↓',
                'sum_fix_link'         => 'See diagnostic ↓',
                // DNS Diagnostic
                'dns_card_title'       => '🔍 DNS Diagnostic — SPF · DKIM Public Key · DMARC',
                'dns_desc'             => 'Verify your DNS records are correctly configured. Scan via Cloudflare DNS-over-HTTPS (port 443 — works on all hosts).',
                'dns_domain_lbl'       => 'Domain',
                'dns_sel_lbl'          => 'DKIM Selector',
                'dns_scan_btn'         => '🔍 Run DNS Scan',
                'dns_manual_lbl'       => 'Manual check via MXToolbox:',
                'dns_to_fix'           => 'To fix',
                'dns_missing'          => 'Missing / Error',
                'lic_renew'            => 'Renew',
                'dns_all_ok'           => 'Perfect! SPF, DKIM and DMARC are correctly configured. Your emails will no longer land in spam.',
                // Nouveaux strings complets v11
                'test_card_title'         => '📋 Send License Report',
                'test_btn'                => '📨 Send license report',
                'test_send_to_lbl'        => 'Sending to',
                'test_success_msg'        => 'Email sent to',
                'test_fail_msg'           => 'Failed:',
                'sender_card_title_lbl'   => '✉️ Sender',
                'pwd_encrypted_note'      => '🔒 Password encrypted in DB (AES-256-CBC). Leave blank to keep.',
                'pwd_aes_note'            => 'Encrypted with <strong>AES-256-CBC</strong> (key: <code>SECURE_AUTH_KEY</code>).',
                'dkim_key_encrypted_note' => '🔒 DKIM private key encrypted in DB (AES-256-CBC).',
                'dns_manual_lbl'          => 'Manual check via MXToolbox:',
                'spf_softfail_lbl'        => 'Policy: ~all (SoftFail)',
                'spf_strict_lbl'          => 'Policy: -all (Strict ✓)',
                'spf_neutral_lbl'         => 'Policy: ?all (Neutral)',
                'dkim_pub_key_lbl'        => 'DKIM Private Key',
                'dkim_scroll_note'        => 'Scroll to see the full key.',
                'dkim_key_size_lbl'       => 'Key size:',
                'dkim_optimal_lbl'        => '✓ (optimal security)',
                'dkim_min_bits_lbl'       => '— minimum recommended: 2048 bits',
                'dmarc_policy_lbl'        => 'Policy:',
                'dmarc_no_rua_warn'       => '⚠ No rua=',
                'dmarc_optional_note'     => 'Optional',
                'dmarc_rua_info'          => '💬 No rua= — you will not receive DMARC reports (optional but recommended).',
                'dmarc_rua_fix'           => '💬 (Optional) Add rua= to receive DMARC reports. Not required for deliverability.',
                'overlay_title'           => 'Activating…',
                'overlay_step1'           => 'Step 1/3 — Validating license key',
                'overlay_step2'           => 'Step 2/3 — DNS analysis',
                'overlay_step3'           => 'Step 3/3 — Filling DKIM fields',
                'overlay_msg1'            => 'Validating license with smtp-dkim.com…',
                'overlay_msg2'            => 'Detecting DKIM selector in your DNS…',
                'overlay_msg4'            => 'Activating…',
                'overlay_sel_found'       => 'DKIM selector detected automatically!',
                'overlay_sel_manual'      => 'Domain configured. Enter your DKIM private key manually.',
                'overlay_alert_empty'     => 'Please enter a license key.',
                'cpanel_steps_title'      => '📍 How to get your DKIM private key from cPanel:',
                'why_not_auto_title'      => 'ℹ️ Why can\'t this key be detected automatically?',
                'why_not_auto_text'       => 'The DNS scan shows your <strong>public key</strong> DKIM — visible to everyone and used to verify the signature. The <strong>private key</strong> is different: it stays secret on your server and is used to sign each email. This is the RSA asymmetric cryptography principle — it is mathematically impossible to deduce the private key from the public key, which guarantees the security of your emails.',
                'lic_max_activations'     => 'Maximum number of activations reached. Contact smtp-dkim.com.',
                'lic_expire_explain_full' => 'ℹ️ <strong>What happens when the license expires:</strong> Your DKIM private key remains saved in your database — it is not deleted. DKIM signing is disabled on all outgoing emails until the license is renewed. Your emails continue to be delivered normally via SMTP, without DKIM signature. <strong>To reactivate:</strong> renew your license at smtp-dkim.com and enter the new key below.',
                'sum_card_title'          => '📋 SMTP-DKIM Configuration',
                'lic_notice_found'        => 'DKIM selector detected automatically:',
                'lic_notice_default'      => 'Default DKIM selector: default (verify in cPanel if needed)',
                'lic_activation_success'  => 'License activated successfully. DKIM signing is now available.',

                'sum_level'            => 'Level',
                // Explanations — all long texts
                'email_from_placeholder'  => 'noreply@your-domain.com',
                'smtp_host_placeholder'   => 'mail.your-domain.com',
                'smtp_host_desc'          => 'SMTP server name provided by your hosting provider.',
                'enc_ssl'                 => 'SSL (port 465)',
                'enc_tls'                 => 'TLS / STARTTLS (port 587)',
                'enc_none'                => 'None (port 25)',
                'auto_tls_desc_full'      => 'Enable automatic upgrade to TLS if available',
                'auth_desc_full'          => 'SMTP Authentication (recommended)',
                'force_from_desc_full'    => 'Force the From address on all outgoing emails',
                'pwd_placeholder_keep'    => '(leave blank to keep current)',
                'pwd_placeholder_new'     => 'Enter SMTP password',
                'dkim_domain_auto_desc'   => '✓ Auto-filled from your WordPress domain',
                'dkim_domain_manual_desc' => 'Leave blank to automatically use the site domain.',
                'dkim_sel_auto_desc'      => '✓ Automatically detected in your DNS — record',
                'dkim_sel_manual_desc'    => 'Automatically detected in DNS when the license is activated.',
                'dkim_key_needed_star'    => '⭐ Paste from cPanel',
                'dkim_key_placeholder'    => "(Paste the full private key from cPanel
→ Email Deliverability → DKIM → View → Private Key)",
                'dkim_key_ok_msg'         => '✓ Private key saved — ',
                'dkim_key_ok_sfx'         => ' characters. DKIM active.',
                'dkim_key_missing_msg'    => '✗ Private key missing — DKIM inactive until this field is filled.',
                'dkim_key_locked_msg'     => 'This field will be available after activating your license.',
                'dkim_cpanel_steps_title' => '📍 How to get your DKIM private key from cPanel:',
                'dkim_cpanel_step1'       => 'Log in to your <strong>cPanel</strong> (your hosting provider)',
                'dkim_cpanel_step2'       => 'Section <strong>Email</strong> → click <strong>Email Deliverability</strong>',
                'dkim_cpanel_step3_pfx'   => 'Find the domain',
                'dkim_cpanel_step3_sfx'   => 'in the list',
                'dkim_cpanel_step4'       => 'Click <strong>Manage</strong> on the right of that domain',
                'dkim_cpanel_step5'       => 'Find the <strong>DKIM</strong> section and click <strong>View</strong>',
                'dkim_cpanel_step6'       => 'Copy the <strong>ENTIRE "Private Key" block</strong>, from the first line',
                'dkim_cpanel_step7'       => 'to the last line',
                'dkim_cpanel_step8'       => 'Paste the key into the text field above',
                'dkim_cpanel_step9'       => 'Click <strong>Save Configuration</strong>',
                'dkim_why_title'          => 'ℹ️ Why can\'t this key be detected automatically?',
                'dkim_why_text'           => 'DKIM uses two keys: the <strong>public key</strong> (in your DNS, detected automatically) verifies the signature. The <strong>private key</strong> signs each email and is <strong>never published in DNS</strong> — it stays secret on your server, ensuring no one else can sign on your behalf. It is stored only in your WordPress database. <strong>No data is sent to smtp-dkim.com servers.</strong>',
                'dkim_where_key_short'    => '📍 Where to find your key: cPanel → <strong>Email Deliverability</strong> → your domain → <strong>DKIM</strong> → <strong>View</strong> → copy <strong>Private Key</strong>',
                'dkim_locked_info_full'   => '🔒 DKIM fields are locked. Purchase and activate a license to unlock them — <a href="https://smtp-dkim.com" target="_blank"><strong>smtp-dkim.com</strong></a>. Once activated, the domain and selector will be filled in automatically.',
                'dkim_active_info_full'   => 'DKIM signature cryptographically signs each outgoing email. Gmail, Outlook and Yahoo verify this signature to confirm the email genuinely comes from your domain and has not been altered in transit.',
                'missing_key_title'       => '⚠️ Last step missing: the DKIM private key',
                'missing_key_body'        => 'Your license is active and the selector was detected automatically. DKIM signing is still <strong>inactive</strong> because the plugin needs your <strong>private key</strong> — it\'s only in <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong>.',
                'missing_key_privacy'     => '🔒 <strong>Privacy:</strong> Your private key is stored only in your WordPress database. <strong>No data is sent to smtp-dkim.com servers.</strong>',
                'need_key_remind_full'    => '⚠️ DKIM private key missing. DKIM signing is inactive. Paste your key from <strong>cPanel → Email Deliverability → DKIM → View → Private Key</strong> then save.',
                'lic_active_label_full'   => '✓ License active',
                'lic_key_lbl'             => 'Key:',
                'lic_holder_lbl'          => 'License holder:',
                'lic_holder_name_lbl'     => 'License holder:',
                'lic_holder_email_lbl'    => 'Holder email:',
                'lic_plan_lbl'            => 'Plan:',
                'lic_domain_lbl'          => 'Domain:',
                'lic_exp_lbl'             => 'Expires:',
                'lic_check_lbl'           => 'Last check:',
                'lic_none_msg'            => '✗ No license registered on this site.',
                'lic_invalid_msg'         => '✗ License invalid or refused by smtp-dkim.com.',
                'lic_deactivated_msg'     => '✗ License inactive — you can reactivate it on this or another site.',
                'lic_expired_msg'         => '⚠️ <strong>License expired.</strong>',
                'lic_expired_explain'     => 'Your DKIM private key remains in the database — it is not deleted. DKIM signing is disabled on all outgoing emails until the license is renewed. Emails continue to be sent via SMTP, without DKIM signing. <strong>To reactivate:</strong> enter a new valid license key below.',
                'lic_buy_link_pfx'        => 'Buy or renew at',
                'lic_buy_link_sfx'        => 'then enter your key:',
                'lic_key_placeholder'     => 'SDKM-XXXXX-XXXXX-XXXXX-XXXXX',
                'lic_activate_note'       => 'The key will be validated in real time. The DKIM domain and selector will be detected automatically.',
                'lic_notice_found'        => 'DKIM selector detected automatically:',
                'lic_notice_default'      => 'DKIM selector set to default (verify in cPanel if needed)',
                'sum_actif'               => 'ACTIVE',
                'sum_inactif'             => 'INACTIVE',
                'sum_buy_lnk'             => 'Buy',
                'sum_check_lnk'           => 'Check',
                'sum_renew_lnk'           => 'Renew',
                'sum_dkim_req'            => '🔒 License required',
                'sum_dkim_nokey'          => '✗ Private key missing',
                'sum_dns_scan_lnk'        => 'Re-run scan ↓',
                'sum_fix_lnk'             => 'See diagnostic ↓',
                'sum_dns_note_full'       => 'DNS verified via Cloudflare DoH.',
                'sum_unconfigured'        => 'Not configured',
                'overlay_step1'           => 'Step 1/3 — Validating license key',
                'overlay_step2'           => 'Step 2/3 — DNS analysis',
                'overlay_step3'           => 'Step 3/3 — Filling DKIM fields',
                'overlay_msg1'            => 'Validating license with smtp-dkim.com...',
                'overlay_msg2'            => 'Detecting DKIM selector in your DNS...',
                'overlay_msg3'            => 'Configuring DKIM fields...',
                'overlay_msg4'            => 'Activating...',
                'overlay_sel_found'       => 'DKIM selector detected automatically!',
                'overlay_sel_manual'      => 'Domain configured. Enter your DKIM private key manually.',
                'overlay_alert_empty'     => 'Please enter a license key.',
                'dns_results_for'         => 'Results for',
                'dns_pub_key_note'        => '🔒 <strong>DKIM Public Key</strong> — visible in DNS, used by Gmail/Outlook to <em>verify</em> your emails. This key is <strong>different</strong> from the private key to paste in the plugin.',
                'dns_fix_optional'        => '💬 Optional information',
                'dns_fix_how'             => '🔧 How to fix — cPanel → Zone Editor',
                'dns_fix_type'            => 'Type',
                'dns_fix_name'            => 'Name',
                'dns_fix_value'           => 'Value',
                'dns_rsa_bits'            => 'bits',
                'dns_optimal'             => '✓ (optimal security)',
                'dns_min_req'             => '— minimum recommended: 2048 bits',
                'dns_alt_sel'             => 'works — update it in the plugin.',
                'lic_card_title_full'     => '🔑 SMTP-DKIM License',
                'test_send_to_lbl'        => 'Sending to',
            ],
        ];
    }
}

// ── PATCH: extra keys injected for full interface translation ──────────────
// This is appended outside the class intentionally as a static helper.
// Call smtpdkimc_Lang_Extra::patch($lang) right after $lang = new smtpdkimc_Lang()
// to merge these keys into the existing dictionary.
// --
// NOTE: This file will be merged cleanly in the next refactor.